version: '3'

services:
  app:
    restart: always
    container_name: pivot
    build:
      context: .
    volumes:
      - ./pivot:/app/pivot
    ports:
      - "8000:8000"
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME:-NONE}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-NONE}
    
